from pydantic import BaseModel
from typing import Optional


class VerifyRequest(BaseModel):
    challengeId: str
    videoStoragePath: str         # Firebase Storage path (e.g. verifications/uid/video.mp4)
    videoDownloadUrl: str         # Short-lived signed download URL generated by Flutter


class VerifyResponse(BaseModel):
    jobId: str
    status: str
    attemptsUsed: int
    attemptsRemaining: int


class StatusResponse(BaseModel):
    jobId: str
    status: str                   # pending | processing | completed | failed
    decision: Optional[str] = None
    score: Optional[float] = None
    message: Optional[str] = None


class AdminActionRequest(BaseModel):
    reason: Optional[str] = None


class AdminStatsResponse(BaseModel):
    pending_review: int
    approved: int
    rejected: int
    total: int
